cron_cron:
    resource: "@CronCronBundle/Resources/config/routing.yml"
    prefix:   /

index:
  pattern:  /
  defaults: { _controller: CronCronBundle:Main:index }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
