cron_cron:
    resource: "@CronCronBundle/Resources/config/routing.yml"
    prefix:   /

index:
  pattern:  /
  defaults: { _controller: CronCronBundle:Main:index }

getStates:
  pattern:  /ajax/getStates
  defaults: { _controller: CronCronBundle:Ajax:getStates }

getCities:
  pattern:  /ajax/getCities
  defaults: { _controller: CronCronBundle:Ajax:getCities }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
